apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: omayma13/devops-project2:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-config

---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
