apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: devops
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/mydb"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "root"
